### ISSUE TITLE
Add support for Stadia API key

### ISSUE THREAD

**Issue by dziban303** [sdr-enthusiasts/docker-virtualradarserver#89]
Add support for parsing the Stadia API key for maps. `EndOfBody.html` from [VRSCustomLayers](https://github.com/rikgale/VRSCustomLayers) is [looking for `##STADIAKEY##`](https://github.com/rikgale/VRSCustomLayers/blob/main/EndOfBody.html#L53); probably docker-compose.yml should have `VRS_ENHANCED_LAYERS_STADIA_APIKEY=` like the others. I don't know what all is needed to do that or I'd do it myself.

Also, the `docker-compose.yml` file in the repo hasn't been updated in some time—it's missing new countries and the Thunderforest key, maybe other stuff, that's present in [the example](https://github.com/sdr-enthusiasts/docker-virtualradarserver?tab=readme-ov-file#example-docker-composeyml) contained within the README.

**Comment by 76rhodan** [comment]
Stadia and Thunderforest envars added. Resolved with b3ae9c5
